name: 博客Api部署 (自动部署)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 设置Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 安装依赖
        run: bun install

      - name: 项目构建打包
        run: bun run build

      - name: 部署到服务器
        uses: appleboy/ssh-action@v0.1.7
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 检查并安装 rsync 工具
          if ! command -v rsync &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y rsync
          fi

          # 创建备份目录
          mkdir -p /www/bokeadminkoa/dist.bak

          # 备份旧文件
          rsync -avz --delete /www/bokeadminkoa/dist/ /www/bokeadminkoa/dist.bak/

          # 上传新文件并排除 public 文件夹
          rsync -avz --delete --exclude "public" dist/ /www/bokeadminkoa/dist/

          # 重启服务
          forever restart /www/bokeadminkoa/dist/src/app.js

          # 检查并导入public文件夹 (如果需要)
          if [ ! -d "/www/bokeadminkoa/dist/public" ]; then
            git init temp-repo
            cd temp-repo
            git remote add origin https://github.com/lzyszds/bokeadminkoa.git
            git config core.sparseCheckout true
            echo "public" >> .git/info/sparse-checkout
            git pull origin master
            mv public /www/bokeadminkoa/dist/
            cd ..
            rm -rf temp-repo
          else
            echo "public 文件夹已存在，跳过克隆。"
          fi
