name: 博客Api部署 (自动部署)

# 提交后的触发器
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 设置Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 安装依赖
        run: bun install

      - name: 项目构建打包
        run: bun run build

      # 删除旧的文件
      - name: 清空旧项目文件
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /www/bokeadminkoa/dist/src/*
            rm -rf /www/bokeadminkoa/dist/config.js

      # 或者如果你只想上传构建后的文件
      - name: 上传构建后的文件
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/"
          target: "/www/bokeadminkoa/"

      - name: 检查并导入文件夹
        run: |
          if [ ! -d "/www/bokeadminkoa/dist/public" ]; then
            git init temp-repo
            cd temp-repo
            git remote add origin https://github.com/lzyszds/bokeadminkoa.git
            git config core.sparseCheckout true
            echo "public" >> .git/info/sparse-checkout
            git pull origin master
            mv public /www/bokeadminkoa/dist/
            cd ..
            rm -rf temp-repo
          else
            echo "public 文件夹已存在，跳过克隆。"
          fi

      # 重启远程服务器上的服务
      - name: 重启服务
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            forever restart /www/bokeadminkoa/dist/src/app.js
