
name: 博客后台部署 (手动触发)

# 手动触发器
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 删除旧的文件
      - name: 清空旧项目文件
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "39.108.89.65"
          username: "root"
          password: Aa395878870
          use_insecure_cipher: true

          script: |
            echo "清空旧的文件..."
          
            echo "删除完成"
      
