name: 博客Api部署 (手动部署)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 设置Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest


      # 删除旧的文件
      - name: 清空旧项目文件
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 39.108.89.65
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /www/server/nodejs/bokeadminkoa/src/*
            rm -rf /www/server/nodejs/bokeadminkoa/config.js

   
